# Site settings
title: Wandering
email: Nashenas88@gmail.com
description: >
  Hi, my name is Paul Fara. This is a place for me to
  share my thoughts on technology, space, etc. I work as a software
  engineer, and I have a huge passion for coding and robotics.
baseurl: ""
url: "http://nashenas88.github.io" # the base hostname & protocol for your site
twitter_username: Nashenas88
github_username:  Nashenas88

# Build settings
markdown: kramdown
highlighter: pygments
