# Site settings
title: Wandering
email: pauldfaria@gmail.com
description: >
  Hi, my name is Paul Faria. This is a place for me to
  share my thoughts on technology, space, etc. I work as a software
  engineer, and I have a huge passion for coding and robotics.
baseurl: ""
include: [_wips]
url: "https://nashenas88.github.io"
title_description: "Title description"
title_image: "https://pbs.twimg.com/profile_images/612406747685191681/6PRxbC2J_400x400.jpg"
google_analytics: "UA-64460630-1"
disqus_account: nashenas88
post_limit: 5

# Social media accounts
twitter_username: Nashenas88
github_username:  Nashenas88
google_plus_username: PaulFaria
linkedin_id: PaulFaria
stackoverflow_id_name: 1483396/nashenas

# Build settings
markdown: kramdown
highlighter: pygments
permalink: '/posts/:title'
